export enum Modals {
    OVERFLOW_MENU_BLOCK = "overflow-menu-block",
    OVERFLOW_MENU_ACTION = "overflow-menu-action",
    dispatchActionConfigOnSelect = "on_item_selected",
    dispatchActionConfigOnInput = "on_character_entered",
    ADDITIONAL_CONFIG = "additionalConfig",
    DROPDOWN = "dropDown",
    INPUTFIELD = "inputField",
    OPTIONS = "options",
    MISSING = "missing",
    VIEWERROR = "viewError",
    DATA = "data",
    ADDITIONAL_PROP = "additionalProperties",
    GROUPS = "groups",
    PROPERTY = "property",
    VALUE = "value",
    CONFIGURE_BLOCK = "configure-block",
    CONFIGURE_ACTION = "configure-action",
    MAIN_CLOSE_BLOCK = "main-close-block",
    MAIN_CLOSE_ACTION = "main-close-action",
    SELECT_LLM_BLOCK = "select-llm-block",
    SELECT_LLM_ACTION = "select-llm-action",
    SELECT_LAN_BLOCK = "select-lan-block",
    SELECT_LAN_ACTION = "select-lan-action",
}
