export enum SubcommandEnum {
    HELP = 'help',
    TEST = 'test',
    UI = 'ui',
    SEARCH = 'search',
    NEW_ISSUE = 'issue',
    ISSUES = 'issues',
    PROFILE = 'me',
    CREATE= 'create',
    LIST ='list',
    REGEN = 'regen',
    GITHUB_LOGIN = 'gh_login',
    GITHUB_LOGOUT = 'gh_logout',
    GITHUB_UPLOAD = 'gh_upload',
    GITHUB_PULL = 'gh_pull',
}
